// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Data;

#nullable disable

namespace Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260504140349_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Web.Models.Bike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CurrentStationId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CurrentStationId");

                    b.ToTable("Bikes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "BIkE-001",
                            CurrentStationId = 1,
                            IsActive = true,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 2,
                            Code = "BIkE-002",
                            CurrentStationId = 1,
                            IsActive = true,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 3,
                            Code = "BIkE-003",
                            CurrentStationId = 2,
                            IsActive = true,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 4,
                            Code = "BIkE-004",
                            CurrentStationId = 3,
                            IsActive = true,
                            Status = "Service"
                        },
                        new
                        {
                            Id = 5,
                            Code = "BIkE-005",
                            CurrentStationId = 3,
                            IsActive = true,
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("Web.Models.BikeStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BikeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("RentalId")
                        .HasColumnType("int");

                    b.Property<int?>("StationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BikeId");

                    b.HasIndex("RentalId");

                    b.HasIndex("StationId");

                    b.ToTable("BikeStatusHistory", (string)null);
                });

            modelBuilder.Entity("Web.Models.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BikeId")
                        .HasColumnType("int");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("EndStationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("StartStationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BikeId");

                    b.HasIndex("EndStationId");

                    b.HasIndex("StartStationId");

                    b.HasIndex("UserId");

                    b.ToTable("Rentals", (string)null);
                });

            modelBuilder.Entity("Web.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Stations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Vsb",
                            IsActive = true,
                            Latitude = 1.000000m,
                            Longitude = 1.000000m,
                            Name = "Skola"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Frydecka",
                            IsActive = true,
                            Latitude = 2.000000m,
                            Longitude = 2.000000m,
                            Name = "Frydek"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Studentska",
                            IsActive = true,
                            Latitude = 3.000000m,
                            Longitude = 3.000000m,
                            Name = "Koleje"
                        });
                });

            modelBuilder.Entity("Web.Models.Bike", b =>
                {
                    b.HasOne("Web.Models.Station", "CurrentStation")
                        .WithMany("Bikes")
                        .HasForeignKey("CurrentStationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentStation");
                });

            modelBuilder.Entity("Web.Models.BikeStatusHistory", b =>
                {
                    b.HasOne("Web.Models.Bike", "Bike")
                        .WithMany("StatusHistory")
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.Models.Rental", "Rental")
                        .WithMany()
                        .HasForeignKey("RentalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Web.Models.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Bike");

                    b.Navigation("Rental");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Web.Models.Rental", b =>
                {
                    b.HasOne("Web.Models.Bike", "Bike")
                        .WithMany("Rentals")
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Web.Models.Station", "EndStation")
                        .WithMany("FinishedRentals")
                        .HasForeignKey("EndStationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Web.Models.Station", "StartStation")
                        .WithMany("StartedRentals")
                        .HasForeignKey("StartStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Web.Models.ApplicationUser", "User")
                        .WithMany("Rentals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bike");

                    b.Navigation("EndStation");

                    b.Navigation("StartStation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Web.Models.ApplicationUser", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("Web.Models.Bike", b =>
                {
                    b.Navigation("Rentals");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Web.Models.Station", b =>
                {
                    b.Navigation("Bikes");

                    b.Navigation("FinishedRentals");

                    b.Navigation("StartedRentals");
                });
#pragma warning restore 612, 618
        }
    }
}
